#!/bin/bash 
  
NAME="demo"                                 # Name of the application 
DJANGODIR=/home/kanishk/Documents/practice_django/try_celery         # Django project directory 
SOCKFILE=/home/kanishk/Documents/practice_django/try_celery/run/gunicorn.sock # we will communicte using this unix socket 
USER=kanishk                                       # the user to run as 
GROUP=kanishk                                    # the group to run as 
NUM_WORKERS=3                                    # how many worker processes should Gunicorn spawn 
DJANGO_SETTINGS_MODULE=try_celery.settings            # which settings file should Django use 
DJANGO_WSGI_MODULE=try_celery.wsgi                    # WSGI module name 
  
echo "Starting $NAME as `whoami`" 
  
# Activate the virtual environment 
cd $DJANGODIR 
Source ../env/bin/activate 
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE 
export PYTHONPATH=$DJANGODIR:$PYTHONPATH 
  
# Create the run directory if it doesn't exist 
RUNDIR=$(dirname $SOCKFILE) 
test -d $RUNDIR || mkdir -p $RUNDIR 
  
# Start your Django Unicorn 
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon) 
exec /home/kanishk/Documents/practice_django/env/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \ 
 --name $NAME \ 
 --workers $NUM_WORKERS \ 
 --user=$USER --group=$GROUP \ 
 --bind=$SOCKFILE \ 
 --log-level=debug \ 
 --log-file=- 